name: deploy_event_service
on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{deploy.SSH_HOST}}
          user: ${{deploy.SSH_USER}}
          private_key: ${{deploy.SSH_PRIVATE_KEY}}
          command: |
            cd event_service
            git checkout dev;
            git pull;
            docker-compose --file docker-compose.prod.yml down;
            docker-compose --file docker-compose.prod.yml up -d;
            ~/go/bin goose -dir migrations "postgresql://${{deploy.PSQL_USERNAME}}:${{deploy.PSQL_PASSWORD}}@${{deploy.PSQL_HOST}}:${{deploy.PSQL_DBPORT}}/${{deploy.PSQL_DBNAME}}?sslmode=disable" up
